2023-05-02 23:51:59,614 INFO: User's cart after update: [{'item_id': ObjectId('644fdd1527d4a8df36e00e34'), 'quantity': 4}, {'item_id': ObjectId('644f37bf711edbcbf5887c1e'), 'quantity': 2}, {'item_id': ObjectId('644fdda027d4a8df36e00e37'), 'quantity': 1}, {'item_id': ObjectId('644fddc527d4a8df36e00e3a'), 'quantity': 1}, {'item_id': ObjectId('644fde0327d4a8df36e00e3d'), 'quantity': 1}] [in /app/app.py:338]
2023-05-02 23:58:38,497 INFO: Application startup [in /app/app.py:71]
2023-05-02 23:59:04,267 ERROR: Exception on /shoppingcart [GET] [in /usr/local/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 301, in shopping_cart
    cart_summary = calculate_cart_summary(items)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 136, in calculate_cart_summary
    subtotal = sum(item["price"] * item["quantity"] for item in items)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2023-05-03 00:01:04,116 INFO: Application startup [in /app/app.py:71]
2023-05-03 00:01:30,047 INFO: Application startup [in /app/app.py:71]
